# Render configuration file
services:
  - type: web
    name: precipitation-analysis
    env: python
    rootDir: moab_precipitation_app
    buildCommand: pip install -r requirements.txt
    startCommand: python app.py
    envVars:
      - key: PORT
        value: 5000
      - key: PYTHON_VERSION
        value: 3.11.0

